### ISSUE TITLE
No longer working with Foundry v0.9, DnD 5e

### ISSUE THREAD

**Issue by magroader** [mclemente/healthEstimate#54]
Just updated to Foundry version 0.9.something (01/05/2022)

Using Health Estimate v26.12

As a Trusted Player I am not able to see the Health Estimate tooltip any longer.

In addition, I tried to open up Style or Death settings, and I get this error:

```
foundry.js:316 Error: This is not a registered game setting
[Detected 1 package: healthEstimate]
    at ClientSettings.get (foundry.js:2115)
    at sGet (modules/healthEstimate/module/utils.js:77)
    at prepSetting (modules/healthEstimate/module/styleSettings.js:66)
    at HealthEstimateStyleSettings.getData (modules/healthEstimate/module/styleSettings.js:73)
    at HealthEstimateStyleSettings._render (foundry.js:3031)
    at HealthEstimateStyleSettings._render (foundry.js:3733)
    at HealthEstimateStyleSettings.render (foundry.js:2990)
    at ExtendedSettingsConfig._onClickSubmenu (foundry.js:55267)
    at HTMLButtonElement.dispatch (jquery.min.js:2)
    at HTMLButtonElement.v.handle (jquery.min.js:2)
```

Possibly of note: a lot of mods went through a lot of upheaval, so if there's some mod that Health Estimate accidentally relies on, it is possible that mod is currently disabled.

**Comment by mclemente** [comment]
Reinstall the module and that should fix it.
