### ISSUE TITLE
Error on startup since update to V9

### ISSUE THREAD

**Issue by CaosFR** [mclemente/healthEstimate#52]
Hi,

Since update to foundry v9 I can't use healthEstimate. I have some errors on startup when healthEstimate is on : 

Foundry : V9
Build : 238
DnD 5e : 1.5.6

SOLVED : I have reinstall as you mentionned here : https://github.com/mclemente/healthEstimate/issues/51

Thanks for your job and help.

```
dnd5e.js:35 Uncaught (in promise) TypeError: t(...).join is not a function
[Detected 1 package: healthEstimate]
    at Module.settings (dnd5e.js:35)
    at systemSpecifics.js:90
  | settings | @ | dnd5e.js:35
  | (anonymous) | @ | systemSpecifics.js:90
  | Promise.then (async) |   |  
  | (anonymous) | @ | systemSpecifics.js:87
  | prepareSystemSpecifics | @ | systemSpecifics.js:79
  | (anonymous) | @ | healthEstimate.js:20
  | _call | @ | foundry.js:294
  | callAll | @ | foundry.js:253
  | setupGame | @ | foundry.js:5466
  | _initializeGameView | @ | foundry.js:6434
  | _initializeView | @ | foundry.js:6410
  | initialize | @ | foundry.js:5380
  | await in initialize (async) |   |  
  | 🎁call_wrapped | @ | libWrapper-wrapper.js:502
  | 🎁libWrapperInit | @ | libWrapper-api.js:778
  | await in 🎁libWrapperInit (async) |   |  
  | 🎁Game.prototype.initialize#0 | @ | libWrapper-wrapper.js:182
  | window.addEventListener.once | @ | foundry.js:62192
```

```
foundry.js:316 Error: This is not a registered game setting
[Detected 1 package: healthEstimate]
    at ClientSettings.get (foundry.js:2115)
    at sGet (utils.js:77)
    at updateSettings (logic.js:98)
    at new HealthEstimate (logic.js:238)
    at healthEstimate.js:31
    at Function._call (foundry.js:294)
    at Function.call (foundry.js:279)
    at Canvas.draw (foundry.js:19879)
    at async Scene.view (foundry.js:17642)
    at async Game.initializeCanvas (foundry.js:5615)
    at async Game.setupGame (foundry.js:5484)
    at async Game._initializeGameView (foundry.js:6434)
    at async Game.initialize (foundry.js:5380)
  | onError | @ | foundry.js:316
  | 🎁call_wrapped | @ | libWrapper-wrapper.js:502
  | 🎁Hooks.onError#lib-wrapper | @ | listeners.js:137
  | 🎁Hooks.onError#0 | @ | libWrapper-wrapper.js:182
  | _call | @ | foundry.js:298
  | call | @ | foundry.js:279
  | draw | @ | foundry.js:19879
  | await in draw (async) |   |  
  | view | @ | foundry.js:17642
  | Scene.view | @ | monks-tokenbar.js:107
  | initializeCanvas | @ | foundry.js:5615
  | await in initializeCanvas (async) |   |  
  | setupGame | @ | foundry.js:5484
  | await in setupGame (async) |   |  
  | _initializeGameView | @ | foundry.js:6434
  | _initializeView | @ | foundry.js:6410
  | initialize | @ | foundry.js:5380
  | await in initialize (async) |   |  
  | 🎁call_wrapped | @ | libWrapper-wrapper.js:502
  | 🎁libWrapperInit | @ | libWrapper-api.js:778
  | await in 🎁libWrapperInit (async) |   |  
  | 🎁Game.prototype.initialize#0 | @ | libWrapper-wrapper.js:182
  | window.addEventListener.once | @ | foundry.js:62192
```

If I try to change "Style Setting" or "Death Setting" I got this : 

```
foundry.js:316 Error: This is not a registered game setting
[Detected 3 packages: healthEstimate, colorsettings, lib-wrapper]
    at ClientSettings.get (foundry.js:2115)
    at sGet (utils.js:77)
    at prepSetting (styleSettings.js:66)
    at HealthEstimateStyleSettings.getData (styleSettings.js:73)
    at HealthEstimateStyleSettings._render (foundry.js:3031)
    at HealthEstimateStyleSettings._render (foundry.js:3733)
    at HealthEstimateStyleSettings.render (foundry.js:2990)
    at ExtendedSettingsConfig.onClickSubmenuWrapper (colorSetting.js:20)
    at Z.🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:586)
    at ExtendedSettingsConfig.🎁SettingsConfig.prototype._onClickSubmenu#0 (libWrapper-wrapper.js:184)
    at HTMLButtonElement.dispatch (jquery.min.js:2)
    at HTMLButtonElement.v.handle (jquery.min.js:2)
```

colorsettings, lib-wrapper are updated and running.
